// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tropcyzebsnrecblpehn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyb3BjeXplYnNucmVjYmxwZWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTAzNjAsImV4cCI6MjA2NzQ2NjM2MH0.7czMyXu5388Co5E2dNiKlxFUFQKk4Rg4vLwG-NWBpas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});